import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./navbar";
import Sidebar from "./sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import { SidebarProvider } from "@/context/SidebarContext";
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SidebarProvider>
        <nav>
          <Navbar />
        </nav>
        <main className="flex flex-row items-center">
          <Sidebar />
          {children}
        </main>
      </SidebarProvider>
    </>
  );
}
